version: '3.9'

services:
  datastore-emulator:
    container_name: datastore-emulator
    image: ghcr.io/marcos-wz/datastore-emulator:latest
    build: .
    environment:
      - CLOUDSDK_CORE_PROJECT=hds-dev
      - GCLOUD_STORE_ON_DISK=true
    volumes:
       - gcloud-cfg:/home/dsuser/.config/gcloud
    ports:
      - 8081:8081
    restart: unless-stopped
  
volumes:
  gcloud-cfg:
